<div class="tred-main block">
	<div class="block-title">
		<strong>TRENDING NOW</strong>
	</div>
	<div class="tred-display">
		<div class="tred">
			<div class="tred-product">
				<div class="title">Processors</div>
				<div class="img"><a href="/components/processors/all-processors.html"><img src="<?php echo $this->getViewFileUrl('images/Processors.jpg'); ?>"/></a></div>
			</div>
		</div>
		<div class="tred">
			<div class="tred-product">
				<div class="title">Headsets</div>
				<div class="img"><a href="/audio-visual/a-v-music-accessories/pc-headsets-headphones.html"><img src="<?php echo $this->getViewFileUrl('images/Headset.jpg'); ?>"/></a></div>
			</div>
		</div>
		<div class="tred">
			<div class="tred-product">
				<div class="title">Motherboards</div>
				<div class="img"><a href="/components/motherboards.html"><img src="<?php echo $this->getViewFileUrl('images/Motherboards.jpg'); ?>"/></a></div>
			</div>
		</div>
		<div class="tred">
			<div class="tred-product">
				<div class="title">Gaming Monitors</div>
				<div class="img"><a href="/displays/computer-displays/gaming-monitors.html"><img src="<?php echo $this->getViewFileUrl('images/Monitors.jpg'); ?>"/></a></div>
			</div>
		</div>
		<div class="tred">
			<div class="tred-product">
				<div class="title">Laptop/Notebooks</div>
				<div class="img"><a href="/computers/notebooks-tablets/notebooks.html"><img src="<?php echo $this->getViewFileUrl('images/Laptops.jpg'); ?>"/></a></div>
			</div>
		</div>
		<div class="tred">
			<div class="tred-product">
				<div class="title">Memory</div>
				<div class="img"><a href="/components/memory.html"><img src="<?php echo $this->getViewFileUrl('images/memory.jpg'); ?>"/></a></div>
			</div>
		</div>
	</div>
</div>